"""Add name column to Bakery model

Revision ID: 720f6990d195
Revises: a50cde241c4b
Create Date: 2023-10-18 12:51:11.701096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720f6990d195'
down_revision = 'a50cde241c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bakeries', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bakeries', 'name')
    # ### end Alembic commands ###
